### ISSUE TITLE
build under R18

### ISSUE THREAD

**Issue by benoitc** [cmullaparthi/ibrowse#129]
build failed under R18 due the the use of `erlang:now()`:

    ibrowse/src/ibrowse_lib.erl:372: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.

**Comment by benoitc** [comment]
Removing the `warning_as_error` option fix it but maybe the call to `erlang:now/0` could be replaced?

**Comment by surik** [comment]
Hi! 
There are four ways to fix it:
  1. Replace `now/0` to `os:timestamp/0` (not to `erlang:timestamp/0` because it doesn't support OTP 17 and older version)
  2. Use `-compile([{nowarn_deprecated_function,[{erlang,now,0}]}]).` for ibrowse_lib.erl and ibrowse_http_client.erl
  3. Use `{erl_opts, [nowarn_deprecate_fucntion]}.` in rebar.config
  4. remove `warning_as_error`

I think 1 is the best way, but I don't sure about correct works `ibrowse_http_client:make_reg_id/0`

**Comment by cmullaparthi** [comment]
An alternative, in the absence of compile time macros to identify pre-R18 erlang, is to modify the ibrowse_http_client:make_req_id/0 to look something like this.

```erlang
make_req_id() ->
    case catch erlang:unqiue_integer() of
        {'EXIT', _} ->
             now();
        V ->
            V
    end.
```

ibrowse_lib.erl can be modified to use os:timestamp/0. Anyone wants to send me a pull request :-)

**Comment by cmullaparthi** [comment]
Thank you @surik for the pull request which fixes this issue.
